
- import_playbook: plays/0_set_ansible_conf.yaml

- import_playbook: plays/1_set_sshd_conf.yaml

- import_playbook: plays/2_set_etc_hosts.yaml

- import_playbook: plays/3_port_check.yaml

- import_playbook: plays/4_install_packages.yaml

- import_playbook: plays/5_stop_firewall.yaml

- import_playbook: plays/6_check_dns.yaml

- import_playbook: plays/7_set_selinux.yaml

#- import_playbook: plays/8_set_add_disk.yaml

- import_playbook: plays/9_docker_file_upload.yaml

- import_playbook: plays/10_install_docker.yaml

- import_playbook: plays/11_unpressure_icp_tar.yaml

- import_playbook: plays/12_make_install_dir.yaml

- import_playbook: plays/13_extract_conf_file.yaml

- import_playbook: plays/14_set_cluster_hosts.yaml

- import_playbook: plays/15_make_images_runtime_dir.yaml
 
- import_playbook: plays/16_move_images_runtime.yaml

- import_playbook: plays/17_move_config_file.yaml

# 설치 환경 구성 최종 검증
- import_playbook: plays/18_check_all_env.yaml

#ansible로 설치 시작 명령어를 내리는데 shell로 변경함
# - import_playbook: plays/19_start_install_icp.yaml
             
