# #15. icp 설치 관련
- name: 15. Preset ICP install'
  hosts: 'boot'
  gather_facts: true
  vars_files:
    - ../../automation_config.yaml
 
  vars:
    icp_install_path: '/opt/ibm-cloud-private-{{ util.icp_ver }}'

  tasks:
 #cluster/runtime 추가 할것
    - name: '15-1. Make install image directory'
      file:
        path: '{{ item.path }}'
        state: 'directory'
        mode: 'u=rw,g=r,o=r'
      with_items:
        - { path: '{{ icp_install_path }}/cluster/images' }
        - { path: '{{ icp_install_path }}/cluster/runtime' }
      register: 'result'
    - debug:
        var: 'result.stdout'
