#1. pem 으로 boot를 제외한 노드에 접속후, boot--> 다른 노드간 접속 가능하게 함
- name: '1. Linux Server Provisioning'
  hosts: 'all'
  gather_facts: true
  vars_files:
    - ../../automation_config.yaml

  vars:

 # 각 노드마다 pwd로 접속 할 수 있도록
  tasks:
  - name: '1-1. Change SSH PermitRootLogin'
    lineinfile:
      dest: '{{ item.dest }}'
      regexp: '{{ item.regexp }}'
      line: '{{ item.line }}'
      state: present
      backup: yes
    with_items:
      - { dest: '/etc/ssh/sshd_config', regexp: 'PasswordAuthentication no', line: 'PasswordAuthentication yes'}
      - { dest: '/etc/ssh/sshd_config', regexp: '#PermitRootLogin yes', line: 'PermitRootLogin yes'}
      - { dest: '/etc/ssh/sshd_config', regexp: 'PermitRootLogin no', line: 'PermitRootLogin yes'} 
    notify:
      - restart ssh     
    register: result

  handlers:
  - name: restart ssh
    service:
      name: sshd
      state: restarted
